'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace Quarzo
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="BEWSCredenciales", [Namespace]:="http://tempuri.org/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class BEWSCredenciales
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdUsuariWsField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PasswordWsField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TokenWsField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property IdUsuariWs() As String
            Get
                Return Me.IdUsuariWsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.IdUsuariWsField, value) <> true) Then
                    Me.IdUsuariWsField = value
                    Me.RaisePropertyChanged("IdUsuariWs")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property PasswordWs() As String
            Get
                Return Me.PasswordWsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PasswordWsField, value) <> true) Then
                    Me.PasswordWsField = value
                    Me.RaisePropertyChanged("PasswordWs")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property TokenWs() As String
            Get
                Return Me.TokenWsField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TokenWsField, value) <> true) Then
                    Me.TokenWsField = value
                    Me.RaisePropertyChanged("TokenWs")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="BECrPrestamo", [Namespace]:="http://tempuri.org/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class BECrPrestamo
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CidasociadField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CDetalleLiField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CNumOperacField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DFechaFormField As String
        
        Private NTasaInterField As Decimal
        
        Private NNumCuotasField As Decimal
        
        Private NCuotaRealField As Decimal
        
        Private NAmorPrincField As Decimal
        
        Private NInteresesField As Decimal
        
        Private NCuotaPresField As Decimal
        
        Private NSaldoAnteField As Decimal
        
        Private NAmorPrin2Field As Decimal
        
        Private NSaldoCredField As Decimal
        
        Private NMontoAproField As Decimal
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Cidasociad() As String
            Get
                Return Me.CidasociadField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CidasociadField, value) <> true) Then
                    Me.CidasociadField = value
                    Me.RaisePropertyChanged("Cidasociad")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Property CDetalleLi() As String
            Get
                Return Me.CDetalleLiField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CDetalleLiField, value) <> true) Then
                    Me.CDetalleLiField = value
                    Me.RaisePropertyChanged("CDetalleLi")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public Property CNumOperac() As String
            Get
                Return Me.CNumOperacField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CNumOperacField, value) <> true) Then
                    Me.CNumOperacField = value
                    Me.RaisePropertyChanged("CNumOperac")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public Property DFechaForm() As String
            Get
                Return Me.DFechaFormField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DFechaFormField, value) <> true) Then
                    Me.DFechaFormField = value
                    Me.RaisePropertyChanged("DFechaForm")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=4)>  _
        Public Property NTasaInter() As Decimal
            Get
                Return Me.NTasaInterField
            End Get
            Set
                If (Me.NTasaInterField.Equals(value) <> true) Then
                    Me.NTasaInterField = value
                    Me.RaisePropertyChanged("NTasaInter")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=5)>  _
        Public Property NNumCuotas() As Decimal
            Get
                Return Me.NNumCuotasField
            End Get
            Set
                If (Me.NNumCuotasField.Equals(value) <> true) Then
                    Me.NNumCuotasField = value
                    Me.RaisePropertyChanged("NNumCuotas")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=6)>  _
        Public Property NCuotaReal() As Decimal
            Get
                Return Me.NCuotaRealField
            End Get
            Set
                If (Me.NCuotaRealField.Equals(value) <> true) Then
                    Me.NCuotaRealField = value
                    Me.RaisePropertyChanged("NCuotaReal")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=7)>  _
        Public Property NAmorPrinc() As Decimal
            Get
                Return Me.NAmorPrincField
            End Get
            Set
                If (Me.NAmorPrincField.Equals(value) <> true) Then
                    Me.NAmorPrincField = value
                    Me.RaisePropertyChanged("NAmorPrinc")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=8)>  _
        Public Property NIntereses() As Decimal
            Get
                Return Me.NInteresesField
            End Get
            Set
                If (Me.NInteresesField.Equals(value) <> true) Then
                    Me.NInteresesField = value
                    Me.RaisePropertyChanged("NIntereses")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=9)>  _
        Public Property NCuotaPres() As Decimal
            Get
                Return Me.NCuotaPresField
            End Get
            Set
                If (Me.NCuotaPresField.Equals(value) <> true) Then
                    Me.NCuotaPresField = value
                    Me.RaisePropertyChanged("NCuotaPres")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=10)>  _
        Public Property NSaldoAnte() As Decimal
            Get
                Return Me.NSaldoAnteField
            End Get
            Set
                If (Me.NSaldoAnteField.Equals(value) <> true) Then
                    Me.NSaldoAnteField = value
                    Me.RaisePropertyChanged("NSaldoAnte")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=11)>  _
        Public Property NAmorPrin2() As Decimal
            Get
                Return Me.NAmorPrin2Field
            End Get
            Set
                If (Me.NAmorPrin2Field.Equals(value) <> true) Then
                    Me.NAmorPrin2Field = value
                    Me.RaisePropertyChanged("NAmorPrin2")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=12)>  _
        Public Property NSaldoCred() As Decimal
            Get
                Return Me.NSaldoCredField
            End Get
            Set
                If (Me.NSaldoCredField.Equals(value) <> true) Then
                    Me.NSaldoCredField = value
                    Me.RaisePropertyChanged("NSaldoCred")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=13)>  _
        Public Property NMontoApro() As Decimal
            Get
                Return Me.NMontoAproField
            End Get
            Set
                If (Me.NMontoAproField.Equals(value) <> true) Then
                    Me.NMontoAproField = value
                    Me.RaisePropertyChanged("NMontoApro")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="BEDeDeducAso", [Namespace]:="http://tempuri.org/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class BEDeDeducAso
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CIdAsociadField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private cDesDeduccField As String
        
        Private nSaldoAnteField As Decimal
        
        Private nMtoCuotasField As Decimal
        
        Private nDepositosField As Decimal
        
        Private nRetiroAhoField As Decimal
        
        Private nInterMoviField As Decimal
        
        Private nPorceTasaField As Decimal
        
        Private nMtoPrinciField As Decimal
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property CIdAsociad() As String
            Get
                Return Me.CIdAsociadField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CIdAsociadField, value) <> true) Then
                    Me.CIdAsociadField = value
                    Me.RaisePropertyChanged("CIdAsociad")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property cDesDeducc() As String
            Get
                Return Me.cDesDeduccField
            End Get
            Set
                If (Object.ReferenceEquals(Me.cDesDeduccField, value) <> true) Then
                    Me.cDesDeduccField = value
                    Me.RaisePropertyChanged("cDesDeducc")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property nSaldoAnte() As Decimal
            Get
                Return Me.nSaldoAnteField
            End Get
            Set
                If (Me.nSaldoAnteField.Equals(value) <> true) Then
                    Me.nSaldoAnteField = value
                    Me.RaisePropertyChanged("nSaldoAnte")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=3)>  _
        Public Property nMtoCuotas() As Decimal
            Get
                Return Me.nMtoCuotasField
            End Get
            Set
                If (Me.nMtoCuotasField.Equals(value) <> true) Then
                    Me.nMtoCuotasField = value
                    Me.RaisePropertyChanged("nMtoCuotas")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=4)>  _
        Public Property nDepositos() As Decimal
            Get
                Return Me.nDepositosField
            End Get
            Set
                If (Me.nDepositosField.Equals(value) <> true) Then
                    Me.nDepositosField = value
                    Me.RaisePropertyChanged("nDepositos")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=5)>  _
        Public Property nRetiroAho() As Decimal
            Get
                Return Me.nRetiroAhoField
            End Get
            Set
                If (Me.nRetiroAhoField.Equals(value) <> true) Then
                    Me.nRetiroAhoField = value
                    Me.RaisePropertyChanged("nRetiroAho")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=6)>  _
        Public Property nInterMovi() As Decimal
            Get
                Return Me.nInterMoviField
            End Get
            Set
                If (Me.nInterMoviField.Equals(value) <> true) Then
                    Me.nInterMoviField = value
                    Me.RaisePropertyChanged("nInterMovi")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=7)>  _
        Public Property nPorceTasa() As Decimal
            Get
                Return Me.nPorceTasaField
            End Get
            Set
                If (Me.nPorceTasaField.Equals(value) <> true) Then
                    Me.nPorceTasaField = value
                    Me.RaisePropertyChanged("nPorceTasa")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=8)>  _
        Public Property nMtoPrinci() As Decimal
            Get
                Return Me.nMtoPrinciField
            End Get
            Set
                If (Me.nMtoPrinciField.Equals(value) <> true) Then
                    Me.nMtoPrinciField = value
                    Me.RaisePropertyChanged("nMtoPrinci")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="BECODisponible", [Namespace]:="http://tempuri.org/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class BECODisponible
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CIdAsociadField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CDetalleLiField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CCodigoLinField As String
        
        Private NDisponibleField As Decimal
        
        Private nDiponiPorcField As Decimal
        
        Private nCapaciPagoField As Decimal
        
        Private nEndeduPorcField As Decimal
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property CIdAsociad() As String
            Get
                Return Me.CIdAsociadField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CIdAsociadField, value) <> true) Then
                    Me.CIdAsociadField = value
                    Me.RaisePropertyChanged("CIdAsociad")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Property CDetalleLi() As String
            Get
                Return Me.CDetalleLiField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CDetalleLiField, value) <> true) Then
                    Me.CDetalleLiField = value
                    Me.RaisePropertyChanged("CDetalleLi")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public Property CCodigoLin() As String
            Get
                Return Me.CCodigoLinField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CCodigoLinField, value) <> true) Then
                    Me.CCodigoLinField = value
                    Me.RaisePropertyChanged("CCodigoLin")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=3)>  _
        Public Property NDisponible() As Decimal
            Get
                Return Me.NDisponibleField
            End Get
            Set
                If (Me.NDisponibleField.Equals(value) <> true) Then
                    Me.NDisponibleField = value
                    Me.RaisePropertyChanged("NDisponible")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=4)>  _
        Public Property nDiponiPorc() As Decimal
            Get
                Return Me.nDiponiPorcField
            End Get
            Set
                If (Me.nDiponiPorcField.Equals(value) <> true) Then
                    Me.nDiponiPorcField = value
                    Me.RaisePropertyChanged("nDiponiPorc")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=5)>  _
        Public Property nCapaciPago() As Decimal
            Get
                Return Me.nCapaciPagoField
            End Get
            Set
                If (Me.nCapaciPagoField.Equals(value) <> true) Then
                    Me.nCapaciPagoField = value
                    Me.RaisePropertyChanged("nCapaciPago")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=6)>  _
        Public Property nEndeduPorc() As Decimal
            Get
                Return Me.nEndeduPorcField
            End Get
            Set
                If (Me.nEndeduPorcField.Equals(value) <> true) Then
                    Me.nEndeduPorcField = value
                    Me.RaisePropertyChanged("nEndeduPorc")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="BECrResulSolicCred", [Namespace]:="http://tempuri.org/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class BECrResulSolicCred
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private pResultadoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MensajeExcField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property pResultado() As String
            Get
                Return Me.pResultadoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.pResultadoField, value) <> true) Then
                    Me.pResultadoField = value
                    Me.RaisePropertyChanged("pResultado")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Property MensajeExc() As String
            Get
                Return Me.MensajeExcField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MensajeExcField, value) <> true) Then
                    Me.MensajeExcField = value
                    Me.RaisePropertyChanged("MensajeExc")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="BEDeducRRHH", [Namespace]:="http://tempuri.org/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class BEDeducRRHH
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private cidasociadField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private cnombreasoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ccodpresupField As String
        
        Private nmontomoviField As Decimal
        
        Private dfechacortField As System.Nullable(Of Date)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private cinstuasocField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private cnombinstiField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property cidasociad() As String
            Get
                Return Me.cidasociadField
            End Get
            Set
                If (Object.ReferenceEquals(Me.cidasociadField, value) <> true) Then
                    Me.cidasociadField = value
                    Me.RaisePropertyChanged("cidasociad")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property cnombreaso() As String
            Get
                Return Me.cnombreasoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.cnombreasoField, value) <> true) Then
                    Me.cnombreasoField = value
                    Me.RaisePropertyChanged("cnombreaso")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public Property ccodpresup() As String
            Get
                Return Me.ccodpresupField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ccodpresupField, value) <> true) Then
                    Me.ccodpresupField = value
                    Me.RaisePropertyChanged("ccodpresup")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=3)>  _
        Public Property nmontomovi() As Decimal
            Get
                Return Me.nmontomoviField
            End Get
            Set
                If (Me.nmontomoviField.Equals(value) <> true) Then
                    Me.nmontomoviField = value
                    Me.RaisePropertyChanged("nmontomovi")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=4)>  _
        Public Property dfechacort() As System.Nullable(Of Date)
            Get
                Return Me.dfechacortField
            End Get
            Set
                If (Me.dfechacortField.Equals(value) <> true) Then
                    Me.dfechacortField = value
                    Me.RaisePropertyChanged("dfechacort")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=5)>  _
        Public Property cinstuasoc() As String
            Get
                Return Me.cinstuasocField
            End Get
            Set
                If (Object.ReferenceEquals(Me.cinstuasocField, value) <> true) Then
                    Me.cinstuasocField = value
                    Me.RaisePropertyChanged("cinstuasoc")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=6)>  _
        Public Property cnombinsti() As String
            Get
                Return Me.cnombinstiField
            End Get
            Set
                If (Object.ReferenceEquals(Me.cnombinstiField, value) <> true) Then
                    Me.cnombinstiField = value
                    Me.RaisePropertyChanged("cnombinsti")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="Quarzo.ServiceNubeAseconstruPlazaSoap")>  _
    Public Interface ServiceNubeAseconstruPlazaSoap
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento bEWSCredenciales del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Met_CreditosPorAsociado", ReplyAction:="*")>  _
        Function Met_CreditosPorAsociado(ByVal request As Quarzo.Met_CreditosPorAsociadoRequest) As Quarzo.Met_CreditosPorAsociadoResponse
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento bEWSCredenciales del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Met_AhorrosPorAsociado", ReplyAction:="*")>  _
        Function Met_AhorrosPorAsociado(ByVal request As Quarzo.Met_AhorrosPorAsociadoRequest) As Quarzo.Met_AhorrosPorAsociadoResponse
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento bEWSCredenciales del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Met_DisponiblePorAsociado", ReplyAction:="*")>  _
        Function Met_DisponiblePorAsociado(ByVal request As Quarzo.Met_DisponiblePorAsociadoRequest) As Quarzo.Met_DisponiblePorAsociadoResponse
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento beCrendenciales del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Met_Solicitud_Credito", ReplyAction:="*")>  _
        Function Met_Solicitud_Credito(ByVal request As Quarzo.Met_Solicitud_CreditoRequest) As Quarzo.Met_Solicitud_CreditoResponse
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento beCrendenciales del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Met_Obtiene_Deducciones_RRHH", ReplyAction:="*")>  _
        Function Met_Obtiene_Deducciones_RRHH(ByVal request As Quarzo.Met_Obtiene_Deducciones_RRHHRequest) As Quarzo.Met_Obtiene_Deducciones_RRHHResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class Met_CreditosPorAsociadoRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Met_CreditosPorAsociado", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As Quarzo.Met_CreditosPorAsociadoRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As Quarzo.Met_CreditosPorAsociadoRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Met_CreditosPorAsociadoRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public bEWSCredenciales As Quarzo.BEWSCredenciales
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public cidasociad As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal bEWSCredenciales As Quarzo.BEWSCredenciales, ByVal cidasociad As String)
            MyBase.New
            Me.bEWSCredenciales = bEWSCredenciales
            Me.cidasociad = cidasociad
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class Met_CreditosPorAsociadoResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Met_CreditosPorAsociadoResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As Quarzo.Met_CreditosPorAsociadoResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As Quarzo.Met_CreditosPorAsociadoResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Met_CreditosPorAsociadoResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public Met_CreditosPorAsociadoResult() As Quarzo.BECrPrestamo
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Met_CreditosPorAsociadoResult() As Quarzo.BECrPrestamo)
            MyBase.New
            Me.Met_CreditosPorAsociadoResult = Met_CreditosPorAsociadoResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class Met_AhorrosPorAsociadoRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Met_AhorrosPorAsociado", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As Quarzo.Met_AhorrosPorAsociadoRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As Quarzo.Met_AhorrosPorAsociadoRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Met_AhorrosPorAsociadoRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public bEWSCredenciales As Quarzo.BEWSCredenciales
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public cidasociad As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal bEWSCredenciales As Quarzo.BEWSCredenciales, ByVal cidasociad As String)
            MyBase.New
            Me.bEWSCredenciales = bEWSCredenciales
            Me.cidasociad = cidasociad
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class Met_AhorrosPorAsociadoResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Met_AhorrosPorAsociadoResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As Quarzo.Met_AhorrosPorAsociadoResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As Quarzo.Met_AhorrosPorAsociadoResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Met_AhorrosPorAsociadoResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public Met_AhorrosPorAsociadoResult() As Quarzo.BEDeDeducAso
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Met_AhorrosPorAsociadoResult() As Quarzo.BEDeDeducAso)
            MyBase.New
            Me.Met_AhorrosPorAsociadoResult = Met_AhorrosPorAsociadoResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class Met_DisponiblePorAsociadoRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Met_DisponiblePorAsociado", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As Quarzo.Met_DisponiblePorAsociadoRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As Quarzo.Met_DisponiblePorAsociadoRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Met_DisponiblePorAsociadoRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public bEWSCredenciales As Quarzo.BEWSCredenciales
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public cidasociad As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal bEWSCredenciales As Quarzo.BEWSCredenciales, ByVal cidasociad As String)
            MyBase.New
            Me.bEWSCredenciales = bEWSCredenciales
            Me.cidasociad = cidasociad
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class Met_DisponiblePorAsociadoResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Met_DisponiblePorAsociadoResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As Quarzo.Met_DisponiblePorAsociadoResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As Quarzo.Met_DisponiblePorAsociadoResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Met_DisponiblePorAsociadoResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public Met_DisponiblePorAsociadoResult As Quarzo.BECODisponible
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Met_DisponiblePorAsociadoResult As Quarzo.BECODisponible)
            MyBase.New
            Me.Met_DisponiblePorAsociadoResult = Met_DisponiblePorAsociadoResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class Met_Solicitud_CreditoRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Met_Solicitud_Credito", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As Quarzo.Met_Solicitud_CreditoRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As Quarzo.Met_Solicitud_CreditoRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Met_Solicitud_CreditoRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public beCrendenciales As Quarzo.BEWSCredenciales
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public cidasociad As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=2)>  _
        Public pMontoCred As Decimal
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=3)>  _
        Public pPlazoCred As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public cCodigolin As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=5)>  _
        Public pComentari As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal beCrendenciales As Quarzo.BEWSCredenciales, ByVal cidasociad As String, ByVal pMontoCred As Decimal, ByVal pPlazoCred As Integer, ByVal cCodigolin As String, ByVal pComentari As String)
            MyBase.New
            Me.beCrendenciales = beCrendenciales
            Me.cidasociad = cidasociad
            Me.pMontoCred = pMontoCred
            Me.pPlazoCred = pPlazoCred
            Me.cCodigolin = cCodigolin
            Me.pComentari = pComentari
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class Met_Solicitud_CreditoResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Met_Solicitud_CreditoResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As Quarzo.Met_Solicitud_CreditoResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As Quarzo.Met_Solicitud_CreditoResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Met_Solicitud_CreditoResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public Met_Solicitud_CreditoResult As Quarzo.BECrResulSolicCred
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Met_Solicitud_CreditoResult As Quarzo.BECrResulSolicCred)
            MyBase.New
            Me.Met_Solicitud_CreditoResult = Met_Solicitud_CreditoResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class Met_Obtiene_Deducciones_RRHHRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Met_Obtiene_Deducciones_RRHH", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As Quarzo.Met_Obtiene_Deducciones_RRHHRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As Quarzo.Met_Obtiene_Deducciones_RRHHRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Met_Obtiene_Deducciones_RRHHRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public beCrendenciales As Quarzo.BEWSCredenciales
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Prm_Tabla As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public Prm_feccorte As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public prm_cinstusoc As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal beCrendenciales As Quarzo.BEWSCredenciales, ByVal Prm_Tabla As String, ByVal Prm_feccorte As String, ByVal prm_cinstusoc As String)
            MyBase.New
            Me.beCrendenciales = beCrendenciales
            Me.Prm_Tabla = Prm_Tabla
            Me.Prm_feccorte = Prm_feccorte
            Me.prm_cinstusoc = prm_cinstusoc
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class Met_Obtiene_Deducciones_RRHHResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="Met_Obtiene_Deducciones_RRHHResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As Quarzo.Met_Obtiene_Deducciones_RRHHResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As Quarzo.Met_Obtiene_Deducciones_RRHHResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Met_Obtiene_Deducciones_RRHHResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public Met_Obtiene_Deducciones_RRHHResult() As Quarzo.BEDeducRRHH
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Met_Obtiene_Deducciones_RRHHResult() As Quarzo.BEDeducRRHH)
            MyBase.New
            Me.Met_Obtiene_Deducciones_RRHHResult = Met_Obtiene_Deducciones_RRHHResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ServiceNubeAseconstruPlazaSoapChannel
        Inherits Quarzo.ServiceNubeAseconstruPlazaSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ServiceNubeAseconstruPlazaSoapClient
        Inherits System.ServiceModel.ClientBase(Of Quarzo.ServiceNubeAseconstruPlazaSoap)
        Implements Quarzo.ServiceNubeAseconstruPlazaSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Quarzo_ServiceNubeAseconstruPlazaSoap_Met_CreditosPorAsociado(ByVal request As Quarzo.Met_CreditosPorAsociadoRequest) As Quarzo.Met_CreditosPorAsociadoResponse Implements Quarzo.ServiceNubeAseconstruPlazaSoap.Met_CreditosPorAsociado
            Return MyBase.Channel.Met_CreditosPorAsociado(request)
        End Function
        
        Public Function Met_CreditosPorAsociado(ByVal bEWSCredenciales As Quarzo.BEWSCredenciales, ByVal cidasociad As String) As Quarzo.BECrPrestamo()
            Dim inValue As Quarzo.Met_CreditosPorAsociadoRequest = New Quarzo.Met_CreditosPorAsociadoRequest()
            inValue.Body = New Quarzo.Met_CreditosPorAsociadoRequestBody()
            inValue.Body.bEWSCredenciales = bEWSCredenciales
            inValue.Body.cidasociad = cidasociad
            Dim retVal As Quarzo.Met_CreditosPorAsociadoResponse = CType(Me,Quarzo.ServiceNubeAseconstruPlazaSoap).Met_CreditosPorAsociado(inValue)
            Return retVal.Body.Met_CreditosPorAsociadoResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Quarzo_ServiceNubeAseconstruPlazaSoap_Met_AhorrosPorAsociado(ByVal request As Quarzo.Met_AhorrosPorAsociadoRequest) As Quarzo.Met_AhorrosPorAsociadoResponse Implements Quarzo.ServiceNubeAseconstruPlazaSoap.Met_AhorrosPorAsociado
            Return MyBase.Channel.Met_AhorrosPorAsociado(request)
        End Function
        
        Public Function Met_AhorrosPorAsociado(ByVal bEWSCredenciales As Quarzo.BEWSCredenciales, ByVal cidasociad As String) As Quarzo.BEDeDeducAso()
            Dim inValue As Quarzo.Met_AhorrosPorAsociadoRequest = New Quarzo.Met_AhorrosPorAsociadoRequest()
            inValue.Body = New Quarzo.Met_AhorrosPorAsociadoRequestBody()
            inValue.Body.bEWSCredenciales = bEWSCredenciales
            inValue.Body.cidasociad = cidasociad
            Dim retVal As Quarzo.Met_AhorrosPorAsociadoResponse = CType(Me,Quarzo.ServiceNubeAseconstruPlazaSoap).Met_AhorrosPorAsociado(inValue)
            Return retVal.Body.Met_AhorrosPorAsociadoResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Quarzo_ServiceNubeAseconstruPlazaSoap_Met_DisponiblePorAsociado(ByVal request As Quarzo.Met_DisponiblePorAsociadoRequest) As Quarzo.Met_DisponiblePorAsociadoResponse Implements Quarzo.ServiceNubeAseconstruPlazaSoap.Met_DisponiblePorAsociado
            Return MyBase.Channel.Met_DisponiblePorAsociado(request)
        End Function
        
        Public Function Met_DisponiblePorAsociado(ByVal bEWSCredenciales As Quarzo.BEWSCredenciales, ByVal cidasociad As String) As Quarzo.BECODisponible
            Dim inValue As Quarzo.Met_DisponiblePorAsociadoRequest = New Quarzo.Met_DisponiblePorAsociadoRequest()
            inValue.Body = New Quarzo.Met_DisponiblePorAsociadoRequestBody()
            inValue.Body.bEWSCredenciales = bEWSCredenciales
            inValue.Body.cidasociad = cidasociad
            Dim retVal As Quarzo.Met_DisponiblePorAsociadoResponse = CType(Me,Quarzo.ServiceNubeAseconstruPlazaSoap).Met_DisponiblePorAsociado(inValue)
            Return retVal.Body.Met_DisponiblePorAsociadoResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Quarzo_ServiceNubeAseconstruPlazaSoap_Met_Solicitud_Credito(ByVal request As Quarzo.Met_Solicitud_CreditoRequest) As Quarzo.Met_Solicitud_CreditoResponse Implements Quarzo.ServiceNubeAseconstruPlazaSoap.Met_Solicitud_Credito
            Return MyBase.Channel.Met_Solicitud_Credito(request)
        End Function
        
        Public Function Met_Solicitud_Credito(ByVal beCrendenciales As Quarzo.BEWSCredenciales, ByVal cidasociad As String, ByVal pMontoCred As Decimal, ByVal pPlazoCred As Integer, ByVal cCodigolin As String, ByVal pComentari As String) As Quarzo.BECrResulSolicCred
            Dim inValue As Quarzo.Met_Solicitud_CreditoRequest = New Quarzo.Met_Solicitud_CreditoRequest()
            inValue.Body = New Quarzo.Met_Solicitud_CreditoRequestBody()
            inValue.Body.beCrendenciales = beCrendenciales
            inValue.Body.cidasociad = cidasociad
            inValue.Body.pMontoCred = pMontoCred
            inValue.Body.pPlazoCred = pPlazoCred
            inValue.Body.cCodigolin = cCodigolin
            inValue.Body.pComentari = pComentari
            Dim retVal As Quarzo.Met_Solicitud_CreditoResponse = CType(Me,Quarzo.ServiceNubeAseconstruPlazaSoap).Met_Solicitud_Credito(inValue)
            Return retVal.Body.Met_Solicitud_CreditoResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Quarzo_ServiceNubeAseconstruPlazaSoap_Met_Obtiene_Deducciones_RRHH(ByVal request As Quarzo.Met_Obtiene_Deducciones_RRHHRequest) As Quarzo.Met_Obtiene_Deducciones_RRHHResponse Implements Quarzo.ServiceNubeAseconstruPlazaSoap.Met_Obtiene_Deducciones_RRHH
            Return MyBase.Channel.Met_Obtiene_Deducciones_RRHH(request)
        End Function
        
        Public Function Met_Obtiene_Deducciones_RRHH(ByVal beCrendenciales As Quarzo.BEWSCredenciales, ByVal Prm_Tabla As String, ByVal Prm_feccorte As String, ByVal prm_cinstusoc As String) As Quarzo.BEDeducRRHH()
            Dim inValue As Quarzo.Met_Obtiene_Deducciones_RRHHRequest = New Quarzo.Met_Obtiene_Deducciones_RRHHRequest()
            inValue.Body = New Quarzo.Met_Obtiene_Deducciones_RRHHRequestBody()
            inValue.Body.beCrendenciales = beCrendenciales
            inValue.Body.Prm_Tabla = Prm_Tabla
            inValue.Body.Prm_feccorte = Prm_feccorte
            inValue.Body.prm_cinstusoc = prm_cinstusoc
            Dim retVal As Quarzo.Met_Obtiene_Deducciones_RRHHResponse = CType(Me,Quarzo.ServiceNubeAseconstruPlazaSoap).Met_Obtiene_Deducciones_RRHH(inValue)
            Return retVal.Body.Met_Obtiene_Deducciones_RRHHResult
        End Function
    End Class
End Namespace
