'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
'
Namespace com.quarzo.gestiones1
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ServiceNubeAseconstruPlazaSoap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ServiceNubeAseconstruPlaza
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private Met_CreditosPorAsociadoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private Met_AhorrosPorAsociadoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private Met_DisponiblePorAsociadoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private Met_Solicitud_CreditoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private Met_Obtiene_Deducciones_RRHHOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.Matching_vb.My.MySettings.Default.Matching_vb_com_quarzo_gestiones1_ServiceNubeAseconstruPlaza
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event Met_CreditosPorAsociadoCompleted As Met_CreditosPorAsociadoCompletedEventHandler
        
        '''<remarks/>
        Public Event Met_AhorrosPorAsociadoCompleted As Met_AhorrosPorAsociadoCompletedEventHandler
        
        '''<remarks/>
        Public Event Met_DisponiblePorAsociadoCompleted As Met_DisponiblePorAsociadoCompletedEventHandler
        
        '''<remarks/>
        Public Event Met_Solicitud_CreditoCompleted As Met_Solicitud_CreditoCompletedEventHandler
        
        '''<remarks/>
        Public Event Met_Obtiene_Deducciones_RRHHCompleted As Met_Obtiene_Deducciones_RRHHCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Met_CreditosPorAsociado", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Met_CreditosPorAsociado(ByVal bEWSCredenciales As BEWSCredenciales, ByVal cidasociad As String) As BECrPrestamo()
            Dim results() As Object = Me.Invoke("Met_CreditosPorAsociado", New Object() {bEWSCredenciales, cidasociad})
            Return CType(results(0),BECrPrestamo())
        End Function
        
        '''<remarks/>
        Public Overloads Sub Met_CreditosPorAsociadoAsync(ByVal bEWSCredenciales As BEWSCredenciales, ByVal cidasociad As String)
            Me.Met_CreditosPorAsociadoAsync(bEWSCredenciales, cidasociad, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Met_CreditosPorAsociadoAsync(ByVal bEWSCredenciales As BEWSCredenciales, ByVal cidasociad As String, ByVal userState As Object)
            If (Me.Met_CreditosPorAsociadoOperationCompleted Is Nothing) Then
                Me.Met_CreditosPorAsociadoOperationCompleted = AddressOf Me.OnMet_CreditosPorAsociadoOperationCompleted
            End If
            Me.InvokeAsync("Met_CreditosPorAsociado", New Object() {bEWSCredenciales, cidasociad}, Me.Met_CreditosPorAsociadoOperationCompleted, userState)
        End Sub
        
        Private Sub OnMet_CreditosPorAsociadoOperationCompleted(ByVal arg As Object)
            If (Not (Me.Met_CreditosPorAsociadoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Met_CreditosPorAsociadoCompleted(Me, New Met_CreditosPorAsociadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Met_AhorrosPorAsociado", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Met_AhorrosPorAsociado(ByVal bEWSCredenciales As BEWSCredenciales, ByVal cidasociad As String) As BEDeDeducAso()
            Dim results() As Object = Me.Invoke("Met_AhorrosPorAsociado", New Object() {bEWSCredenciales, cidasociad})
            Return CType(results(0),BEDeDeducAso())
        End Function
        
        '''<remarks/>
        Public Overloads Sub Met_AhorrosPorAsociadoAsync(ByVal bEWSCredenciales As BEWSCredenciales, ByVal cidasociad As String)
            Me.Met_AhorrosPorAsociadoAsync(bEWSCredenciales, cidasociad, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Met_AhorrosPorAsociadoAsync(ByVal bEWSCredenciales As BEWSCredenciales, ByVal cidasociad As String, ByVal userState As Object)
            If (Me.Met_AhorrosPorAsociadoOperationCompleted Is Nothing) Then
                Me.Met_AhorrosPorAsociadoOperationCompleted = AddressOf Me.OnMet_AhorrosPorAsociadoOperationCompleted
            End If
            Me.InvokeAsync("Met_AhorrosPorAsociado", New Object() {bEWSCredenciales, cidasociad}, Me.Met_AhorrosPorAsociadoOperationCompleted, userState)
        End Sub
        
        Private Sub OnMet_AhorrosPorAsociadoOperationCompleted(ByVal arg As Object)
            If (Not (Me.Met_AhorrosPorAsociadoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Met_AhorrosPorAsociadoCompleted(Me, New Met_AhorrosPorAsociadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Met_DisponiblePorAsociado", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Met_DisponiblePorAsociado(ByVal bEWSCredenciales As BEWSCredenciales, ByVal cidasociad As String) As BECODisponible
            Dim results() As Object = Me.Invoke("Met_DisponiblePorAsociado", New Object() {bEWSCredenciales, cidasociad})
            Return CType(results(0),BECODisponible)
        End Function
        
        '''<remarks/>
        Public Overloads Sub Met_DisponiblePorAsociadoAsync(ByVal bEWSCredenciales As BEWSCredenciales, ByVal cidasociad As String)
            Me.Met_DisponiblePorAsociadoAsync(bEWSCredenciales, cidasociad, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Met_DisponiblePorAsociadoAsync(ByVal bEWSCredenciales As BEWSCredenciales, ByVal cidasociad As String, ByVal userState As Object)
            If (Me.Met_DisponiblePorAsociadoOperationCompleted Is Nothing) Then
                Me.Met_DisponiblePorAsociadoOperationCompleted = AddressOf Me.OnMet_DisponiblePorAsociadoOperationCompleted
            End If
            Me.InvokeAsync("Met_DisponiblePorAsociado", New Object() {bEWSCredenciales, cidasociad}, Me.Met_DisponiblePorAsociadoOperationCompleted, userState)
        End Sub
        
        Private Sub OnMet_DisponiblePorAsociadoOperationCompleted(ByVal arg As Object)
            If (Not (Me.Met_DisponiblePorAsociadoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Met_DisponiblePorAsociadoCompleted(Me, New Met_DisponiblePorAsociadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Met_Solicitud_Credito", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Met_Solicitud_Credito(ByVal beCrendenciales As BEWSCredenciales, ByVal cidasociad As String, ByVal pMontoCred As Decimal, ByVal pPlazoCred As Integer, ByVal cCodigolin As String, ByVal pComentari As String) As BECrResulSolicCred
            Dim results() As Object = Me.Invoke("Met_Solicitud_Credito", New Object() {beCrendenciales, cidasociad, pMontoCred, pPlazoCred, cCodigolin, pComentari})
            Return CType(results(0),BECrResulSolicCred)
        End Function
        
        '''<remarks/>
        Public Overloads Sub Met_Solicitud_CreditoAsync(ByVal beCrendenciales As BEWSCredenciales, ByVal cidasociad As String, ByVal pMontoCred As Decimal, ByVal pPlazoCred As Integer, ByVal cCodigolin As String, ByVal pComentari As String)
            Me.Met_Solicitud_CreditoAsync(beCrendenciales, cidasociad, pMontoCred, pPlazoCred, cCodigolin, pComentari, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Met_Solicitud_CreditoAsync(ByVal beCrendenciales As BEWSCredenciales, ByVal cidasociad As String, ByVal pMontoCred As Decimal, ByVal pPlazoCred As Integer, ByVal cCodigolin As String, ByVal pComentari As String, ByVal userState As Object)
            If (Me.Met_Solicitud_CreditoOperationCompleted Is Nothing) Then
                Me.Met_Solicitud_CreditoOperationCompleted = AddressOf Me.OnMet_Solicitud_CreditoOperationCompleted
            End If
            Me.InvokeAsync("Met_Solicitud_Credito", New Object() {beCrendenciales, cidasociad, pMontoCred, pPlazoCred, cCodigolin, pComentari}, Me.Met_Solicitud_CreditoOperationCompleted, userState)
        End Sub
        
        Private Sub OnMet_Solicitud_CreditoOperationCompleted(ByVal arg As Object)
            If (Not (Me.Met_Solicitud_CreditoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Met_Solicitud_CreditoCompleted(Me, New Met_Solicitud_CreditoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Met_Obtiene_Deducciones_RRHH", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Met_Obtiene_Deducciones_RRHH(ByVal beCrendenciales As BEWSCredenciales, ByVal Prm_Tabla As String, ByVal Prm_feccorte As String, ByVal prm_cinstusoc As String) As BEDeducRRHH()
            Dim results() As Object = Me.Invoke("Met_Obtiene_Deducciones_RRHH", New Object() {beCrendenciales, Prm_Tabla, Prm_feccorte, prm_cinstusoc})
            Return CType(results(0),BEDeducRRHH())
        End Function
        
        '''<remarks/>
        Public Overloads Sub Met_Obtiene_Deducciones_RRHHAsync(ByVal beCrendenciales As BEWSCredenciales, ByVal Prm_Tabla As String, ByVal Prm_feccorte As String, ByVal prm_cinstusoc As String)
            Me.Met_Obtiene_Deducciones_RRHHAsync(beCrendenciales, Prm_Tabla, Prm_feccorte, prm_cinstusoc, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Met_Obtiene_Deducciones_RRHHAsync(ByVal beCrendenciales As BEWSCredenciales, ByVal Prm_Tabla As String, ByVal Prm_feccorte As String, ByVal prm_cinstusoc As String, ByVal userState As Object)
            If (Me.Met_Obtiene_Deducciones_RRHHOperationCompleted Is Nothing) Then
                Me.Met_Obtiene_Deducciones_RRHHOperationCompleted = AddressOf Me.OnMet_Obtiene_Deducciones_RRHHOperationCompleted
            End If
            Me.InvokeAsync("Met_Obtiene_Deducciones_RRHH", New Object() {beCrendenciales, Prm_Tabla, Prm_feccorte, prm_cinstusoc}, Me.Met_Obtiene_Deducciones_RRHHOperationCompleted, userState)
        End Sub
        
        Private Sub OnMet_Obtiene_Deducciones_RRHHOperationCompleted(ByVal arg As Object)
            If (Not (Me.Met_Obtiene_Deducciones_RRHHCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Met_Obtiene_Deducciones_RRHHCompleted(Me, New Met_Obtiene_Deducciones_RRHHCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class BEWSCredenciales
        
        Private idUsuariWsField As String
        
        Private passwordWsField As String
        
        Private tokenWsField As String
        
        '''<remarks/>
        Public Property IdUsuariWs() As String
            Get
                Return Me.idUsuariWsField
            End Get
            Set
                Me.idUsuariWsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PasswordWs() As String
            Get
                Return Me.passwordWsField
            End Get
            Set
                Me.passwordWsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TokenWs() As String
            Get
                Return Me.tokenWsField
            End Get
            Set
                Me.tokenWsField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class BEDeducRRHH
        
        Private cidasociadField As String
        
        Private cnombreasoField As String
        
        Private ccodpresupField As String
        
        Private nmontomoviField As Decimal
        
        Private dfechacortField As System.Nullable(Of Date)
        
        Private cinstuasocField As String
        
        Private cnombinstiField As String
        
        '''<remarks/>
        Public Property cidasociad() As String
            Get
                Return Me.cidasociadField
            End Get
            Set
                Me.cidasociadField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property cnombreaso() As String
            Get
                Return Me.cnombreasoField
            End Get
            Set
                Me.cnombreasoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ccodpresup() As String
            Get
                Return Me.ccodpresupField
            End Get
            Set
                Me.ccodpresupField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property nmontomovi() As Decimal
            Get
                Return Me.nmontomoviField
            End Get
            Set
                Me.nmontomoviField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(IsNullable:=true)>  _
        Public Property dfechacort() As System.Nullable(Of Date)
            Get
                Return Me.dfechacortField
            End Get
            Set
                Me.dfechacortField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property cinstuasoc() As String
            Get
                Return Me.cinstuasocField
            End Get
            Set
                Me.cinstuasocField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property cnombinsti() As String
            Get
                Return Me.cnombinstiField
            End Get
            Set
                Me.cnombinstiField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class BECrResulSolicCred
        
        Private pResultadoField As String
        
        Private mensajeExcField As String
        
        '''<remarks/>
        Public Property pResultado() As String
            Get
                Return Me.pResultadoField
            End Get
            Set
                Me.pResultadoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MensajeExc() As String
            Get
                Return Me.mensajeExcField
            End Get
            Set
                Me.mensajeExcField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class BECODisponible
        
        Private cIdAsociadField As String
        
        Private cDetalleLiField As String
        
        Private cCodigoLinField As String
        
        Private nDisponibleField As Decimal
        
        Private nDiponiPorcField As Decimal
        
        Private nCapaciPagoField As Decimal
        
        Private nEndeduPorcField As Decimal
        
        '''<remarks/>
        Public Property CIdAsociad() As String
            Get
                Return Me.cIdAsociadField
            End Get
            Set
                Me.cIdAsociadField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CDetalleLi() As String
            Get
                Return Me.cDetalleLiField
            End Get
            Set
                Me.cDetalleLiField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CCodigoLin() As String
            Get
                Return Me.cCodigoLinField
            End Get
            Set
                Me.cCodigoLinField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NDisponible() As Decimal
            Get
                Return Me.nDisponibleField
            End Get
            Set
                Me.nDisponibleField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property nDiponiPorc() As Decimal
            Get
                Return Me.nDiponiPorcField
            End Get
            Set
                Me.nDiponiPorcField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property nCapaciPago() As Decimal
            Get
                Return Me.nCapaciPagoField
            End Get
            Set
                Me.nCapaciPagoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property nEndeduPorc() As Decimal
            Get
                Return Me.nEndeduPorcField
            End Get
            Set
                Me.nEndeduPorcField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class BEDeDeducAso
        
        Private cIdAsociadField As String
        
        Private cDesDeduccField As String
        
        Private nSaldoAnteField As Decimal
        
        Private nMtoCuotasField As Decimal
        
        Private nDepositosField As Decimal
        
        Private nRetiroAhoField As Decimal
        
        Private nInterMoviField As Decimal
        
        Private nPorceTasaField As Decimal
        
        Private nMtoPrinciField As Decimal
        
        '''<remarks/>
        Public Property CIdAsociad() As String
            Get
                Return Me.cIdAsociadField
            End Get
            Set
                Me.cIdAsociadField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property cDesDeducc() As String
            Get
                Return Me.cDesDeduccField
            End Get
            Set
                Me.cDesDeduccField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property nSaldoAnte() As Decimal
            Get
                Return Me.nSaldoAnteField
            End Get
            Set
                Me.nSaldoAnteField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property nMtoCuotas() As Decimal
            Get
                Return Me.nMtoCuotasField
            End Get
            Set
                Me.nMtoCuotasField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property nDepositos() As Decimal
            Get
                Return Me.nDepositosField
            End Get
            Set
                Me.nDepositosField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property nRetiroAho() As Decimal
            Get
                Return Me.nRetiroAhoField
            End Get
            Set
                Me.nRetiroAhoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property nInterMovi() As Decimal
            Get
                Return Me.nInterMoviField
            End Get
            Set
                Me.nInterMoviField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property nPorceTasa() As Decimal
            Get
                Return Me.nPorceTasaField
            End Get
            Set
                Me.nPorceTasaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property nMtoPrinci() As Decimal
            Get
                Return Me.nMtoPrinciField
            End Get
            Set
                Me.nMtoPrinciField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class BECrPrestamo
        
        Private cidasociadField As String
        
        Private cDetalleLiField As String
        
        Private cNumOperacField As String
        
        Private dFechaFormField As String
        
        Private nTasaInterField As Decimal
        
        Private nNumCuotasField As Decimal
        
        Private nCuotaRealField As Decimal
        
        Private nAmorPrincField As Decimal
        
        Private nInteresesField As Decimal
        
        Private nCuotaPresField As Decimal
        
        Private nSaldoAnteField As Decimal
        
        Private nAmorPrin2Field As Decimal
        
        Private nSaldoCredField As Decimal
        
        '''<remarks/>
        Public Property Cidasociad() As String
            Get
                Return Me.cidasociadField
            End Get
            Set
                Me.cidasociadField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CDetalleLi() As String
            Get
                Return Me.cDetalleLiField
            End Get
            Set
                Me.cDetalleLiField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CNumOperac() As String
            Get
                Return Me.cNumOperacField
            End Get
            Set
                Me.cNumOperacField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DFechaForm() As String
            Get
                Return Me.dFechaFormField
            End Get
            Set
                Me.dFechaFormField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NTasaInter() As Decimal
            Get
                Return Me.nTasaInterField
            End Get
            Set
                Me.nTasaInterField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NNumCuotas() As Decimal
            Get
                Return Me.nNumCuotasField
            End Get
            Set
                Me.nNumCuotasField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NCuotaReal() As Decimal
            Get
                Return Me.nCuotaRealField
            End Get
            Set
                Me.nCuotaRealField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NAmorPrinc() As Decimal
            Get
                Return Me.nAmorPrincField
            End Get
            Set
                Me.nAmorPrincField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NIntereses() As Decimal
            Get
                Return Me.nInteresesField
            End Get
            Set
                Me.nInteresesField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NCuotaPres() As Decimal
            Get
                Return Me.nCuotaPresField
            End Get
            Set
                Me.nCuotaPresField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NSaldoAnte() As Decimal
            Get
                Return Me.nSaldoAnteField
            End Get
            Set
                Me.nSaldoAnteField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NAmorPrin2() As Decimal
            Get
                Return Me.nAmorPrin2Field
            End Get
            Set
                Me.nAmorPrin2Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NSaldoCred() As Decimal
            Get
                Return Me.nSaldoCredField
            End Get
            Set
                Me.nSaldoCredField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub Met_CreditosPorAsociadoCompletedEventHandler(ByVal sender As Object, ByVal e As Met_CreditosPorAsociadoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Met_CreditosPorAsociadoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As BECrPrestamo()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),BECrPrestamo())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub Met_AhorrosPorAsociadoCompletedEventHandler(ByVal sender As Object, ByVal e As Met_AhorrosPorAsociadoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Met_AhorrosPorAsociadoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As BEDeDeducAso()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),BEDeDeducAso())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub Met_DisponiblePorAsociadoCompletedEventHandler(ByVal sender As Object, ByVal e As Met_DisponiblePorAsociadoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Met_DisponiblePorAsociadoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As BECODisponible
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),BECODisponible)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub Met_Solicitud_CreditoCompletedEventHandler(ByVal sender As Object, ByVal e As Met_Solicitud_CreditoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Met_Solicitud_CreditoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As BECrResulSolicCred
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),BECrResulSolicCred)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub Met_Obtiene_Deducciones_RRHHCompletedEventHandler(ByVal sender As Object, ByVal e As Met_Obtiene_Deducciones_RRHHCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Met_Obtiene_Deducciones_RRHHCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As BEDeducRRHH()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),BEDeducRRHH())
            End Get
        End Property
    End Class
End Namespace
